// Date: 9/4/2015 9:13:29 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer CapTop;
    ModelRenderer CapBack;
    ModelRenderer CapLeft;
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer CapRight;
    ModelRenderer leftarm;
    ModelRenderer CapFrontA;
    ModelRenderer rightleg;
    ModelRenderer CapFrontL;
    ModelRenderer leftleg;
    ModelRenderer CapFrontR;
    ModelRenderer FeatherF;
    ModelRenderer FeatherB;
    ModelRenderer FeatherE;
    ModelRenderer FeatherC;
    ModelRenderer FeatherA;
    ModelRenderer FeatherD;
    ModelRenderer Shape1;
  
  public ModelModel()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      CapTop = new ModelRenderer(this, 0, 53);
      CapTop.addBox(-5F, -9F, -5F, 10, 1, 10);
      CapTop.setRotationPoint(0F, 0F, 0F);
      CapTop.setTextureSize(64, 64);
      CapTop.mirror = true;
      setRotation(CapTop, 0F, 0F, 0F);
      CapBack = new ModelRenderer(this, 18, 48);
      CapBack.addBox(-4F, -8F, 4F, 8, 4, 1);
      CapBack.setRotationPoint(0F, 0F, 0F);
      CapBack.setTextureSize(64, 64);
      CapBack.mirror = true;
      setRotation(CapBack, 0F, 0F, 0F);
      CapLeft = new ModelRenderer(this, 42, 50);
      CapLeft.addBox(-5F, -8F, -5F, 1, 4, 10);
      CapLeft.setRotationPoint(0F, 0F, 0F);
      CapLeft.setTextureSize(64, 64);
      CapLeft.mirror = true;
      setRotation(CapLeft, 0F, 0F, 0F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 40, 16);
      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(64, 64);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      CapRight = new ModelRenderer(this, 42, 50);
      CapRight.addBox(4F, -8F, -5F, 1, 4, 10);
      CapRight.setRotationPoint(0F, 0F, 0F);
      CapRight.setTextureSize(64, 64);
      CapRight.mirror = true;
      setRotation(CapRight, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 40, 16);
      leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(64, 64);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      CapFrontA.mirror = true;
      CapFrontA = new ModelRenderer(this, 0, 50);
      CapFrontA.addBox(-4F, -8F, -4F, 8, 2, 1);
      CapFrontA.setRotationPoint(0F, 0F, -1F);
      CapFrontA.setTextureSize(64, 64);
      CapFrontA.mirror = true;
      setRotation(CapFrontA, 0F, 0F, 0F);
      CapFrontA.mirror = false;
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      rightleg.setRotationPoint(-2F, 12F, 0F);
      rightleg.setTextureSize(64, 64);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      CapFrontL.mirror = true;
      CapFrontL = new ModelRenderer(this, 0, 48);
      CapFrontL.addBox(-4F, -6F, -5F, 1, 1, 1);
      CapFrontL.setRotationPoint(0F, 0F, 0F);
      CapFrontL.setTextureSize(64, 64);
      CapFrontL.mirror = true;
      setRotation(CapFrontL, 0F, 0F, 0F);
      CapFrontL.mirror = false;
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      leftleg.setRotationPoint(2F, 12F, 0F);
      leftleg.setTextureSize(64, 64);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      CapFrontR = new ModelRenderer(this, 0, 48);
      CapFrontR.addBox(3F, -6F, -5F, 1, 1, 1);
      CapFrontR.setRotationPoint(0F, 0F, 0F);
      CapFrontR.setTextureSize(64, 64);
      CapFrontR.mirror = true;
      setRotation(CapFrontR, 0F, 0F, 0F);
      FeatherF = new ModelRenderer(this, 4, 43);
      FeatherF.addBox(-5.5F, -13F, 1F, 1, 1, 6);
      FeatherF.setRotationPoint(0F, 0F, 0F);
      FeatherF.setTextureSize(64, 64);
      FeatherF.mirror = true;
      setRotation(FeatherF, 0F, 0F, 0F);
      FeatherB = new ModelRenderer(this, 8, 45);
      FeatherB.addBox(-5.5F, -10F, -3F, 1, 2, 2);
      FeatherB.setRotationPoint(0F, 0F, 0F);
      FeatherB.setTextureSize(64, 64);
      FeatherB.mirror = true;
      setRotation(FeatherB, 0F, 0F, 0F);
      FeatherE = new ModelRenderer(this, 0, 41);
      FeatherE.addBox(-5.5F, -12F, -1F, 1, 1, 6);
      FeatherE.setRotationPoint(0F, 0F, 0F);
      FeatherE.setTextureSize(64, 64);
      FeatherE.mirror = true;
      setRotation(FeatherE, 0F, 0F, 0F);
      FeatherC = new ModelRenderer(this, 0, 46);
      FeatherC.addBox(-5.5F, -10F, -1F, 1, 1, 1);
      FeatherC.setRotationPoint(0F, 0F, 0F);
      FeatherC.setTextureSize(64, 64);
      FeatherC.mirror = true;
      setRotation(FeatherC, 0F, 0F, 0F);
      FeatherA = new ModelRenderer(this, 4, 48);
      FeatherA.addBox(-5.5F, -8F, -4F, 1, 1, 1);
      FeatherA.setRotationPoint(0F, 0F, 0F);
      FeatherA.setTextureSize(64, 64);
      FeatherA.mirror = true;
      setRotation(FeatherA, 0F, 0F, 0F);
      FeatherD = new ModelRenderer(this, 0, 36);
      FeatherD.addBox(-5.5F, -11F, -2F, 1, 1, 4);
      FeatherD.setRotationPoint(0F, 0F, 0F);
      FeatherD.setTextureSize(64, 64);
      FeatherD.mirror = true;
      setRotation(FeatherD, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 35);
      Shape1.addBox(-5.5F, -14F, 2F, 1, 1, 3);
      Shape1.setRotationPoint(0F, 0F, 1F);
      Shape1.setTextureSize(64, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    CapTop.render(f5);
    CapBack.render(f5);
    CapLeft.render(f5);
    head.render(f5);
    body.render(f5);
    rightarm.render(f5);
    CapRight.render(f5);
    leftarm.render(f5);
    CapFrontA.render(f5);
    rightleg.render(f5);
    CapFrontL.render(f5);
    leftleg.render(f5);
    CapFrontR.render(f5);
    FeatherF.render(f5);
    FeatherB.render(f5);
    FeatherE.render(f5);
    FeatherC.render(f5);
    FeatherA.render(f5);
    FeatherD.render(f5);
    Shape1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
