// Date: 9/4/2015 1:04:30 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelHelmetF extends ModelBase
{
  //fields
    ModelRenderer r2;
    ModelRenderer r1;
    ModelRenderer f2;
    ModelRenderer f1;
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer top;
    ModelRenderer featherBk;
    ModelRenderer featherFr;
    ModelRenderer b1;
    ModelRenderer b2;
    ModelRenderer f1;
    ModelRenderer f2;
    ModelRenderer f3;
    ModelRenderer f4;
    ModelRenderer l1;
    ModelRenderer l2;
    ModelRenderer Shape2;
    ModelRenderer Feather;
    ModelRenderer right;
    ModelRenderer back;
    ModelRenderer front;
    ModelRenderer left;
    ModelRenderer Shape1;
  
  public ModelHelmetF()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      r2.mirror = true;
      r2 = new ModelRenderer(this, 0, 53);
      r2.addBox(-5F, -5F, 0F, 1, 1, 4);
      r2.setRotationPoint(0F, 0F, 0F);
      r2.setTextureSize(64, 64);
      r2.mirror = true;
      setRotation(r2, 0F, 0F, 0F);
      r2.mirror = false;
      r1.mirror = true;
      r1 = new ModelRenderer(this, 0, 42);
      r1.addBox(-5F, -8F, -4F, 1, 3, 8);
      r1.setRotationPoint(0F, 0F, 0F);
      r1.setTextureSize(64, 64);
      r1.mirror = true;
      setRotation(r1, 0F, 0F, 0F);
      r1.mirror = false;
      f2 = new ModelRenderer(this, 36, 0);
      f2.addBox(-0.5F, -13F, -6.5F, 1, 2, 13);
      f2.setRotationPoint(0F, 0F, 0F);
      f2.setTextureSize(64, 64);
      f2.mirror = true;
      setRotation(f2, 0F, 0F, 0F);
      f1 = new ModelRenderer(this, 40, 49);
      f1.addBox(-0.5F, -10F, -5.5F, 1, 1, 11);
      f1.setRotationPoint(0F, 0F, 0F);
      f1.setTextureSize(64, 64);
      f1.mirror = true;
      setRotation(f1, 0F, 0F, 0F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 40, 16);
      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(64, 64);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 40, 16);
      leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(64, 64);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      rightleg.setRotationPoint(-2F, 12F, 0F);
      rightleg.setTextureSize(64, 64);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      leftleg.setRotationPoint(2F, 12F, 0F);
      leftleg.setTextureSize(64, 64);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      top = new ModelRenderer(this, 0, 53);
      top.addBox(-5F, -9F, -5F, 10, 1, 10);
      top.setRotationPoint(0F, 0F, 0F);
      top.setTextureSize(64, 64);
      top.mirror = true;
      setRotation(top, 0F, 0F, 0F);
      featherBk = new ModelRenderer(this, 0, 42);
      featherBk.addBox(-0.5F, -14.5F, 1F, 1, 7, 1);
      featherBk.setRotationPoint(0F, 0F, 0F);
      featherBk.setTextureSize(64, 64);
      featherBk.mirror = true;
      setRotation(featherBk, -0.3956661F, 0F, 0F);
      featherFr = new ModelRenderer(this, 4, 42);
      featherFr.addBox(-0.5F, -14.5F, -2F, 1, 7, 1);
      featherFr.setRotationPoint(0F, 0F, 0F);
      featherFr.setTextureSize(64, 64);
      featherFr.mirror = true;
      setRotation(featherFr, 0.3956661F, 0F, 0F);
      b1 = new ModelRenderer(this, 18, 47);
      b1.addBox(-5F, -8F, 4F, 10, 5, 1);
      b1.setRotationPoint(0F, 0F, 0F);
      b1.setTextureSize(64, 64);
      b1.mirror = true;
      setRotation(b1, 0F, 0F, 0F);
      b2 = new ModelRenderer(this, 18, 45);
      b2.addBox(-3F, -3F, 4F, 6, 1, 1);
      b2.setRotationPoint(0F, 0F, 0F);
      b2.setTextureSize(64, 64);
      b2.mirror = true;
      setRotation(b2, 0F, 0F, 0F);
      f1 = new ModelRenderer(this, 40, 61);
      f1.addBox(-5F, -8F, -5F, 10, 2, 1);
      f1.setRotationPoint(0F, 0F, 0F);
      f1.setTextureSize(64, 64);
      f1.mirror = true;
      setRotation(f1, 0F, 0F, 0F);
      f2 = new ModelRenderer(this, 6, 61);
      f2.addBox(-5F, -6F, -5F, 1, 1, 1);
      f2.setRotationPoint(0F, 0F, 0F);
      f2.setTextureSize(64, 64);
      f2.mirror = true;
      setRotation(f2, 0F, 0F, 0F);
      f3.mirror = true;
      f3 = new ModelRenderer(this, 6, 61);
      f3.addBox(4F, -6F, -5F, 1, 1, 1);
      f3.setRotationPoint(0F, 0F, 0F);
      f3.setTextureSize(64, 64);
      f3.mirror = true;
      setRotation(f3, 0F, 0F, 0F);
      f3.mirror = false;
      f4 = new ModelRenderer(this, 0, 60);
      f4.addBox(-1F, -6F, -5F, 2, 2, 1);
      f4.setRotationPoint(0F, 0F, 0F);
      f4.setTextureSize(64, 64);
      f4.mirror = true;
      setRotation(f4, 0F, 0F, 0F);
      l1 = new ModelRenderer(this, 0, 42);
      l1.addBox(4F, -8F, -4F, 1, 3, 8);
      l1.setRotationPoint(0F, 0F, 0F);
      l1.setTextureSize(64, 64);
      l1.mirror = true;
      setRotation(l1, 0F, 0F, 0F);
      l2 = new ModelRenderer(this, 0, 53);
      l2.addBox(4F, -5F, 0F, 1, 1, 4);
      l2.setRotationPoint(0F, 0F, 0F);
      l2.setTextureSize(64, 64);
      l2.mirror = true;
      setRotation(l2, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 38, 34);
      Shape2.addBox(-0.5F, -11F, -6F, 1, 1, 12);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(64, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
    Feather = new ModelRenderer(this, "Feather");
    Feather.setRotationPoint(0F, 0F, 0F);
    setRotation(Feather, 0.2268928F, 0F, 0F);
    Feather.mirror = true;
      ModelBiped.addChildModelRenderer(Feather);
    right = new ModelRenderer(this, "right");
    right.setRotationPoint(0F, 0F, 0F);
    setRotation(right, 0F, 0F, 0F);
    right.mirror = true;
      ModelBiped.addChildModelRenderer(right);
    back = new ModelRenderer(this, "back");
    back.setRotationPoint(0F, 0F, 0F);
    setRotation(back, 0F, 0F, 0F);
    back.mirror = true;
      ModelBiped.addChildModelRenderer(back);
    front = new ModelRenderer(this, "front");
    front.setRotationPoint(0F, 0F, 0F);
    setRotation(front, 0F, 0F, 0F);
    front.mirror = true;
      ModelBiped.addChildModelRenderer(front);
    left = new ModelRenderer(this, "left");
    left.setRotationPoint(0F, 0F, 0F);
    setRotation(left, 0F, 0F, 0F);
    left.mirror = true;
      ModelBiped.addChildModelRenderer(left);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 1, 7, 1);
      Shape1.setRotationPoint(0F, 0F, 0F);
      Shape1.setTextureSize(64, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0.3956661F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    r2.render(f5);
    r1.render(f5);
    f2.render(f5);
    f1.render(f5);
    head.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
    top.render(f5);
    featherBk.render(f5);
    featherFr.render(f5);
    b1.render(f5);
    b2.render(f5);
    f1.render(f5);
    f2.render(f5);
    f3.render(f5);
    f4.render(f5);
    l1.render(f5);
    l2.render(f5);
    Shape2.render(f5);
    Feather.render(f5);
    right.render(f5);
    back.render(f5);
    front.render(f5);
    left.render(f5);
    Shape1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
